#!/usr/bin/env bash

# Connect to the first server using SSH with the private key ~/.ssh/school and the user ubuntu
ssh -i ~/.ssh/school ubuntu@100.25.162.47

# Connect to the second server using SSH with the private key ~/.ssh/school and the user ubuntu
ssh -i ~/.ssh/school ubuntu@18.210.16.9

